#!/bin/bash
#
# convert-archive-wav.sh — watches an AllStar/HamVOIP recording directory and
# transcodes GSM-in-WAV recordings to linear PCM in place, so they can be
# played back directly in a browser with a plain <audio> tag.
#
# Usage: convert-archive-wav.sh [WATCH_DIR]
#   WATCH_DIR defaults to the VHF node's record directory below; pass a path
#   to reuse this same script on the UHF box (node 53209) unmodified.
#
# Requires: inotify-tools, sox (developed/tested against SoX 14.4.2)
#
# Copyright (C) 2026 Jason Schollenberger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -u

WATCH_DIR="${1:-/etc/asterisk/record/50420}"
LOGFILE="/var/log/recording-converter.log"
LOCKFILE="/var/run/convert-archive-wav.lock"

# Delay after a close_write event before we touch the file. close_write
# already fires only after the writer's fd is closed, so this is just a
# small safety margin, not a real wait-for-completion mechanism. Lower it
# (even to 0) if you don't see "still being written" warnings in the log.
SETTLE_DELAY=1

# ── Preflight ────────────────────────────────────────────────────────────
for bin in inotifywait sox soxi flock; do
    command -v "$bin" >/dev/null 2>&1 || { echo "FATAL: '$bin' not found in PATH." >&2; exit 1; }
done
[[ -d "$WATCH_DIR" ]] || { echo "FATAL: watch directory '$WATCH_DIR' does not exist." >&2; exit 1; }

# ── Singleton guard ──────────────────────────────────────────────────────
# Stops two copies of this script (e.g. a stray cron @reboot entry AND a
# systemd unit) from racing on the same temp filenames.
exec 200>"$LOCKFILE"
flock -n 200 || { echo "Another instance is already running (lock: $LOCKFILE). Exiting." >&2; exit 1; }

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOGFILE"
}

log "Starting watcher on $WATCH_DIR"

# FIX: clean up temp files orphaned by a previous run that was killed
# mid-conversion (between sox writing *_temp.WAV and the mv). The filename
# filter below skips *_temp.wav forever, so without this they'd linger
# permanently. Only remove ones older than 5 minutes so we can never race
# a conversion that is somehow legitimately in flight.
find "$WATCH_DIR" -maxdepth 1 -iname '*_temp.wav' -mmin +5 -print0 2>/dev/null |
    while IFS= read -r -d '' stale; do
        log "Removing stale temp file from previous run: $(basename "$stale")"
        rm -f "$stale"
    done

# Clean shutdown on systemd stop / Ctrl-C. A trap alone can't interrupt a
# blocking `cmd | while read` pipeline -- the shell won't notice SHUTDOWN=1
# until the pipeline itself ends, and inotifywait never gets the signal
# just because its parent did. So the trap kills inotifywait directly by
# PID, which unblocks everything below immediately.
SHUTDOWN=0
INOTIFY_PID=""
trap 'SHUTDOWN=1; [[ -n "$INOTIFY_PID" ]] && kill "$INOTIFY_PID" 2>/dev/null' TERM INT

# Remembers filenames we ourselves just converted (name -> unix timestamp),
# so the moved_to event generated by our OWN "mv temp -> final" below doesn't
# get logged and re-checked as if it were a freshly arrived recording. Keyed
# by filename (not just "the last one") because with several transmissions
# back-to-back, an earlier file's self-triggered event can still be queued
# behind newer files' conversions by the time it's dequeued.
declare -A RECENT_CONVERSIONS

# Total successful conversions this run -- used to report how many of the
# files checked in a catch-up scan actually needed converting.
CONVERTED_COUNT=0

_prune_recent() {
    local now="$1" k
    for k in "${!RECENT_CONVERSIONS[@]}"; do
        (( now - RECENT_CONVERSIONS[$k] > 60 )) && unset "RECENT_CONVERSIONS[$k]"
    done
}

process_file() {
    local NEWFILE="$1"
    local QUIET="${2:-0}"      # 1 = suppress the routine "already PCM" line (used by catch_up_scan)
    local DO_SETTLE="${3:-1}"  # 0 = skip SETTLE_DELAY (pre-existing files can't still be mid-write)

    local NEWFILE_LC="${NEWFILE,,}"

    # Case-insensitive .WAV filter; skip our own temp files outright.
    if [[ "$NEWFILE_LC" != *.wav ]] || [[ "$NEWFILE_LC" == *_temp.wav ]]; then
        return
    fi

    # Swallow the self-triggered moved_to from our own mv() at the bottom of
    # this function -- see the inotifywait test in the review notes for why
    # this fires.
    local NOW
    NOW=$(date +%s)
    _prune_recent "$NOW"
    if [[ -n "${RECENT_CONVERSIONS[$NEWFILE]:-}" ]]; then
        return
    fi

    local INPUT="$WATCH_DIR/$NEWFILE"
    local TEMPFILE="$WATCH_DIR/${NEWFILE%.*}_temp.WAV"

    [[ -f "$INPUT" ]] || return

    [[ "$DO_SETTLE" == "1" ]] && sleep "$SETTLE_DELAY"

    local ENCODING
    ENCODING=$(soxi -e "$INPUT" 2>/dev/null)

    if [[ -z "$ENCODING" ]]; then
        log "WARNING: soxi could not read $NEWFILE (still being written, or not a valid WAV) — skipping this pass; investigate if this repeats for the same file"
        return
    fi

    if [[ "$ENCODING" != "GSM" ]]; then
        [[ "$QUIET" == "1" ]] || log "Skipping $NEWFILE — already PCM (encoding: $ENCODING)"
        return
    fi

    log "Converting GSM file: $NEWFILE"
    if sox -t wav -r 8000 -c 1 -e gsm "$INPUT" -t wav -r 8000 -c 1 -e signed-integer -b 16 "$TEMPFILE" 2>>"$LOGFILE"; then
        if mv "$TEMPFILE" "$INPUT"; then
            RECENT_CONVERSIONS["$NEWFILE"]=$(date +%s)
            ((CONVERTED_COUNT++))
            log "SUCCESS: replaced $NEWFILE with playable PCM version"
        else
            log "FAILED mv for $NEWFILE"
            rm -f "$TEMPFILE" 2>/dev/null
        fi
    else
        log "FAILED conversion for $NEWFILE"
        rm -f "$TEMPFILE" 2>/dev/null
    fi
}

catch_up_scan() {
    local f total=0 before=$CONVERTED_COUNT
    log "Catch-up scan: checking $WATCH_DIR for anything that arrived while not running"
    for f in "$WATCH_DIR"/*; do
        [[ -f "$f" ]] || continue
        ((total++))
        process_file "$(basename "$f")" 1 0
    done
    log "Catch-up scan complete: $total file(s) checked, $((CONVERTED_COUNT - before)) converted"
}

run_watcher() {
    local FIFO="/tmp/.convert-archive-wav.fifo.$$"
    rm -f "$FIFO"
    mkfifo "$FIFO"

    inotifywait -m -e close_write -e moved_to --format '%f' "$WATCH_DIR" 2>>"$LOGFILE" > "$FIFO" &
    INOTIFY_PID=$!

    # Catch up on anything already sitting in WATCH_DIR -- covers a genuine
    # cold start after downtime *and* inotifywait having briefly died and
    # been restarted by the loop below. Runs after inotifywait is already
    # live, so nothing that arrives during the scan itself gets missed: it
    # just queues up in the FIFO and is handled right after, same as any
    # other event (the RECENT_CONVERSIONS guard above quietly no-ops it if
    # the scan already converted it).
    catch_up_scan

    # No pipe here (`< "$FIFO"` is redirection, not a pipe), so this loop runs
    # in the current shell -- RECENT_CONVERSIONS updates in process_file
    # persist correctly across iterations without subshell scoping surprises.
    while read -r NEWFILE; do
        process_file "$NEWFILE"
    done < "$FIFO"

    wait "$INOTIFY_PID" 2>/dev/null
    INOTIFY_PID=""
    rm -f "$FIFO"
}

# ── Watch loop with auto-restart ─────────────────────────────────────────
# If inotifywait ever dies (watch dir briefly unavailable, inotify queue
# overflow, etc.) run_watcher returns and a bare setup would go dark for
# good. This wrapper makes the watcher self-healing, while still exiting
# cleanly on SIGTERM/SIGINT via the trap above.
while (( ! SHUTDOWN )); do
    run_watcher
    if (( SHUTDOWN )); then
        log "Shutdown signal received — exiting cleanly."
        break
    fi
    log "WARNING: inotifywait exited unexpectedly — restarting watch in 5s"
    sleep 5
done
